# https://iwiki.woa.com/pages/viewpage.action?pageId=168736953
source:
  # 文件或目录使用绝对路径，绝对路径按代码库根目录计算，以/开头。
  # 提供产品代码库中编写的测试代码存放目录或文件名格式，以便代码检查时进行排除处理
  # 不要使用.*/等正则表达式屏蔽掉所有代码，会使得代码存在风险，还会导致Coverity扫不到任何代码而失败
  # 提供产品代码库中直接以源码形式存在的第三方代码目录或代码文件名的正则表达。
  # 此处备注的第三方代码将在代码检查时进行排除，若代码库中不存在需要排除的第三方代码，该项配置标识可为空
  third_party_source:
      #第三方代码文件的正则表达式，例如[".*/java/test/.*", ".*/test.java"]
      filepath_regex: [".*/public/.*", ".*eslintrc.js", ".*babel.config.js", ".*/src/views/resourceSplit/.*"]