import Vue from 'vue';
import {
  Button,
  Row,
  Col,
  Form,
  FormItem,
  Input,
  Select,
  Option,
  Message,
  MessageBox,
  Scrollbar,
  Menu,
  MenuItemGroup,
  Submenu,
  MenuItem,
  Tooltip,
  Breadcrumb,
  BreadcrumbItem,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Badge,
  Table,
  TableColumn,
  Tag,
  Tabs,
  TabPane,
  Timeline,
  TimelineItem,
  Card,
  Pagination,
  Notification,
  Dialog,
  DatePicker,
  TimePicker,
  Tree,
  Upload,
  Carousel,
  CarouselItem,
  Rate,
  Container,
  Aside,
  Main,
  Header,
  Footer,
  Progress,
  Popover,
  Descriptions,
  DescriptionsItem,
  Checkbox,
  CheckboxGroup,
  Collapse,
  CollapseItem,
  Steps,
  Step,
  Switch,
  Radio,
  RadioButton,
  RadioGroup,
  Drawer,
  Avatar,
  Empty,
  Autocomplete,
} from 'element-ui';
Message.install = () => {
  Vue.prototype.$message = Message;
};
MessageBox.install = () => {
  Vue.prototype.$confirm = MessageBox.confirm;
};
Notification.install = () => {
  Vue.prototype.$notify = Notification;
};
Notification.install = () => {
  Vue.prototype.$dialog = Dialog;
};

Vue.use(Button);
Vue.use(Row);
Vue.use(Col);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(Message);
Vue.use(MessageBox);
Vue.use(Notification);
Vue.use(Scrollbar);
Vue.use(Menu);
Vue.use(MenuItemGroup);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(Tooltip);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Badge);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Tag);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Timeline);
Vue.use(TimelineItem);
Vue.use(Card);
Vue.use(Pagination);
Vue.use(Dialog);
Vue.use(DatePicker);
Vue.use(TimePicker);
Vue.use(Select);
Vue.use(Option);
Vue.use(Tree);
Vue.use(Upload);
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Rate);
Vue.use(Container);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Header);
Vue.use(Footer);
Vue.use(Progress);
Vue.use(Popover);
Vue.use(Descriptions);
Vue.use(DescriptionsItem);
Vue.use(Checkbox);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(CheckboxGroup);
Vue.use(Steps);
Vue.use(Step);
Vue.use(Switch);
Vue.use(Radio);
Vue.use(RadioButton);
Vue.use(RadioGroup);
Vue.use(Drawer);
Vue.use(Empty);
Vue.use(Avatar);
Vue.use(Autocomplete);
